apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Littlefisher619/argoflow
    targetRevision: 202208270154/my-cluster.my-domain.com
    path: distribution/kubeflow/notebooks/profile-controller_access-management
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
