kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgByHiIDKNO9llAKO0pJTKLHIPW+e+qaVMGwLkIh2iT+0eNh/KCcfet3SV9eagnrZz+iFqKuNYflTsWUUZnRcleGN83wCjYzv4YNaudq6sl6FSKwDtH9s1CB3IMgTOMTsmlMFKXo/xLIMWmcld0v5mH+wEwL3MKs4w6fj5dkbeaob8DO69Q792A/XWJBVGA+dRjosRmYUzK8n3ihjCjk/XT1M9/f9MjUvOT+gCJRGHH9DD7dYEC2+2XDny0nmePB9uzURktXCsQWpOKPXUsdjjErA9H7bpRueLsJyxY8KRXzBjh8SHvOWCHRIT6UOcPsPROx3n93hnfcPaL8UVy7ILcAvEHPxUKe3vT7ewlQ0oSpYl57ZcKllelaIMuI0smitOq2QmlKt9JDZUiNfLBtd7Ix5Oen9S3OuBBnYJTTcydUIVmslGrF4kQaPvoTw7bi+47QadLhnf3NMWYCzOkj/NG8WWYGgDSa5GdQh9AifSbOLWpp8pLBGA2ZD5b8YdDtTHo7TPPqlcvMwRjyr5jJGtZ4MoZ35Pw8laR48QQhZ+HlZhE3qsoxcnVjKKJrxLei/QGwrGd3OPGwkYNAeMBhKnELEszFJoND9rBrGHkbCjFbrMNnlFZj+N8xvAx1tCWICmbeYj+iuLK5uo8bbXjQEAWNGPITjEQfA7hwKrh90pFVauHo7LP2LSGyuCxIrzAI56ax3137CTOV
    admin-user: AgCCgtqFBhc+CTPZx23C8v6enbsfETQQanrL0gekFd6mPkr/2/XV9iArKjb1OD/MQPFz/EG0zJcvRV4KvnOmJlhgdoaAbBTw0mAVxDXjBK1vcJrL7FfsSQO+HpUQrzhv+u5w4NYmiWdGqbUURuPP1LpnjqE2yU2vrYvxmk/SSIGyoWn8cdHAUR1c+U9+bPZsW/6Hpj+7WiFooqAk35Yqwr3hrx33g++xjZyQif3MdYtuwz1h0M3t3/NdRzFwuUfBe4B/HcY5re+3jl1kpoG/p/Ekj5Ua2SM/oxapqTfmqgXY6/nQFA/lXNSY/x/PkpoOOwQ788eMRI6aOWkcTdI1jeMmrj8FZGzKhdS6n99ZBIVWgaB0KU2UvWJLHWBU73xm3TSetWY6GRjvyh3IptM8Rp5sxGOP9rypQsJT/MbM2zNvcz2HggIqAK1nR9+mWO5KmKQttigWA/TLRGZldHesIXcIGFFUR7PfNzAWbaTvOUhY9UNespOQUGUw+yjAhf4njYrExpFnkdFxbgeWAB3R8i/gmUVjFdFJTAM1yS3FQJaoc/UvivHPcQqVCvvspOGDeCz2jnUSzkTTqktSP8nBGLMbQ1hpfn7VX0mdOzysB2LsvtWZuxQ/7c0h3oCGESM+CDR2+1jC8SOT10KjMtt78PVwYfTeKy5SkdMLCetOUbbI3pIGLMA6+XOEPR+l/uXGMO7nIZ+LAw==
