kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBlQ2jPtAV1g/e63qiRuH2r8AkXxoXUS9IcuSccaXtEkEMXlZ7444xrx2njnmpaWxbzJiDp+f8XeB2XT7ZcHIU8cQb09b/9ANmLce5etw1c2RIgS7MGHd4dvP+as7SgCeU6Pjr/7p1uYnByAr1ZVi8pCHzzUOn1tyhSrYfo5h5i22N+hyX3UgouEXGxLhe4fN/FXknnHQm2wnPMLqLhbwsvjE2EOGxQpsGSnYUDa0dL1mcMZRmsfkNc62TNyo2Yxl4pZEymfZYAnWc7KuKv0JANdvJDHEqZjnmcPVxvZSpSWuLGObGx8VlozxgaQxhOA4/9qVgSkvjz0CGg2VK1shrqaSSP22MTKE/7l0mH7O+SopfqyVOnz8a6rs3EdKqxUsWCJdcwvZVU4SSUw8dJ9yR8DUtjrFsue6LZipMuSuw4NgVZ86cs8eioYf67c3jDQTRdB1dDGbucin/7UKCHODqbkvT+/irhyHuHjA+ZJt3kJ2RA7I+IcLQN744+Q0WFbJKSp2LEnfWGGqYY/BTxV404GruCpsTb2pIGYnouDwc3/2qWmx+QYQMLp3EzxT3QbR2ffPHLfYady7TP0++rTmAb9Oj2HWMV/FUGG5LBzsh8wV7IBhWUlu2e9ImHWSSgeJul3p/5m2v3P8wknHOkRCQGChO/ld0Qk53m5XHgh6v12XNX1Qtm64IMB612Wi1jqtlU6pqDrXbI
    admin-user: AgBnPBxyqU2CMkYClCxKpIIXglsGjJL5pdmJKufikVCwCOB7iDJOvYE04nKBBFXIfsc/OO3FbofMOmmp00952x3CS650iKBjYUgtCBnrHx4LaWiLS9EGyYYIq55/VM50vUIDjF9pCObf/Qs9TZUTES7BvBksdPjMJLh20h+sKYJ+nwDYF2v5ntijGj61jiFxsTul1qOH15kDx5b25mNCQr2dMAhlgmV97Bj8p43lfD0NrFMTNaJjOIvVrhCQL9oCdUZttBDsqSrU7lCmJeAffdi2brjwexBUGgBcfRWW34pBZY0rDY2lxbx7kEP0NWbC7HtrOw/ZCr4KC3ryH9T5zWEYk94luVsY1EFbHHtDBWIeoeNCeBNPCQBqERYQaaq3ZTzBvBb5jeh1rTsfv2RfYSwxxRVUzPyJK5wF0QR6V1pzXdphzM1RIeIEDc79p1+L+L+HbiKvsi+BXT/pU2doNeRjmuAIGiSNa2RtdOjupH28CPEz5XU5VboZ2Kf2+YIbLg3u5IwGeFmkYH5veaTUN8IJGBQKOvhFsuCqcA0X01T5fhjTmcb3vl+yytYQ7RDGW05MsA/lT9Z0QcInAqurkTgIyxKfDTJtUGEl+v/OnTe+Gtc305hj2R6pKiGx/ade/KGvUx2laB9Allu6Z6gPuyC4+SqPWQllkdfpffU2YbzfChTOvNIF6b7LOx3yM7QiPN9szNwiHw==
